from sqlalchemy import Column, Integer, String, Float, Date, DateTime, Text
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class BridgeGinkoPDS(Base):
    __tablename__ = 'bridge_ginko_pds'

    id = Column(Integer, primary_key=True, autoincrement=True)
    id_pds = Column(Integer)
    id_pds_ginko = Column(String(255))
    reference = Column(String(255))
    edl_id = Column(Integer)
    edl_reference = Column(String(255))
    edl_typespace = Column(String(255))
    etat = Column(String(255))
    sousetat = Column(String(255))
    coupe = Column(String(255))
    motif_coupure = Column(String(255))
    coupure_accessible = Column(String(255))
    nature = Column(String(255))
    typeinjection = Column(String(255))
    limitation = Column(String(255))
    puissancelimitation = Column(String(255))
    lieulimitation = Column(String(255))
    motiflimitation = Column(String(255))
    puissancelimitetechnique = Column(String(255))
    communicabilite = Column(String(255))
    normecommunicationcpl = Column(String(255))
    ccpiaccessible = Column(String(255))
    emplacementcompteur = Column(String(255))
    accescompteur = Column(String(255))
    accesdisjoncteur = Column(String(255))
    modereleve = Column(String(255))
    typetension = Column(String(255))
    ahautrisquevital = Column(String(255))
    teleoperable = Column(String(255))
    dateteleoperable = Column(Date)
    datebasculecommactive = Column(Date)
    datecreation = Column(Date)
    releveagent_date = Column(Date)
    datemodification = Column(DateTime)
    releveagent_date = Column(Date)
    dateetat = Column(Date)
    dateetatlimitation = Column(Date)
    datemodifniveaucomm = Column(Date)
    datemiseenservice = Column(Date)
    commentaireintervenant = Column(Text)
    niveauouvertureservice = Column(String(255))
    utilisation = Column(String(255))
    centre_code = Column(String(255))
    positiongps_lat = Column(String(255))
    positiongps_lgt = Column(String(255))
    adresse = Column(String(255))
    adresse_compl = Column(String(255))
    codepostal = Column(String(255))
    commune = Column(String(255))
    codeinsee = Column(String(255))
    created_at = Column(DateTime)
