from sqlalchemy import Column, Integer, String, Date, DateTime, Boolean
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class Silencieux(Base):
    __tablename__ = 'silencieux'

    id                         = Column(Integer, primary_key=True)
    priorite                   = Column(String(255), nullable=False)
    cause_silence              = Column(String(255), nullable=True)
    probabilite_defaillance     = Column(String(3), nullable=True)
    presence_da_c              = Column(String(3), nullable=True)
    presence_da_k              = Column(String(3), nullable=True)
    presence_dit_c             = Column(String(3), nullable=True)
    presence_dit_k             = Column(String(3), nullable=True)
    dr                         = Column(String(20), nullable=True)
    affaire_l001               = Column(String(3),  nullable=True)
    agence_intervention        = Column(String(255), nullable=True)
    base_op                    = Column(String(255), nullable=True)
    code_insee                 = Column(String(5),   nullable=True)
    compteur                   = Column(String(255), nullable=True)
    constructeur               = Column(String(255), nullable=True)
    date_ouverture_da_c        = Column(Date,        nullable=True)
    date_derniere_collecte     = Column(Date,        nullable=True)
    id_depart                  = Column(String(20),  nullable=True)
    accessibilite              = Column(String(50),   nullable=True)
    cause_generale             = Column(String(255), nullable=True)
    nb_ligne                   = Column(Integer,     nullable=True)
    nb_jour_non_collecte       = Column(Integer,     nullable=True)
    nb_jour_non_collecte_23h59 = Column(Integer,     nullable=True)
    techno                     = Column(String(10),  nullable=True)
    pdk_com                    = Column(String(255), nullable=True)
    pdkc_egal_pdkr             = Column(String(4),   nullable=True)
    pdk_ref                    = Column(String(255), nullable=True)
    priorite_pilprod           = Column(Integer,     nullable=True)
    prm                        = Column(String(14),  nullable=True, index=True)
    regime                     = Column(String(255), nullable=True)
    statut_contrat             = Column(String(255), nullable=True)
    tranche                    = Column(String(255), nullable=True)
    type_production            = Column(String(255), nullable=True)
    date_import                = Column(DateTime,    nullable=True)
    date_entree_cause_silence  = Column(Date,        nullable=True)
    champs_t                   = Column(String(255), nullable=True)
    etat_silence               = Column(String(255), nullable=True)
    traite                     = Column(Boolean,     nullable=True)
